// ─────────────────────────────────────────────────────────────────────────────
// SUBJECTS
// ─────────────────────────────────────────────────────────────────────────────
export const subjects = [
  { name: 'Computer Science', slug: 'computer-science' },
  { name: 'Law', slug: 'law' },
  { name: 'Medicine & Health', slug: 'medicine' },
  { name: 'Engineering', slug: 'engineering' },
  { name: 'Business & Management', slug: 'business-management' },
  { name: 'Psychology', slug: 'psychology' },
  { name: 'Mathematics & Statistics', slug: 'mathematics' },
  { name: 'Physics', slug: 'physics' },
  { name: 'Economics', slug: 'economics' },
  { name: 'History', slug: 'history' },
  { name: 'Nursing', slug: 'nursing' },
  { name: 'Accounting & Finance', slug: 'accounting-finance' },
  { name: 'Marketing', slug: 'marketing' },
  { name: 'Data Science & AI', slug: 'data-science' },
  { name: 'Architecture & Design', slug: 'architecture' },
]

// ─────────────────────────────────────────────────────────────────────────────
// UNIVERSITIES  (UK · USA · Canada · Australia + worldwide)
// ─────────────────────────────────────────────────────────────────────────────
export const universities = [
  // ── UK ──────────────────────────────────────────────────────────────────
  { name: 'University of Oxford', slug: 'university-of-oxford', location: 'Oxford, England', country: 'UK', established: 1096, ranking: 1, website: 'https://ox.ac.uk', description: 'One of the oldest and most prestigious universities in the world, renowned for research excellence across all disciplines.' },
  { name: 'University of Cambridge', slug: 'university-of-cambridge', location: 'Cambridge, England', country: 'UK', established: 1209, ranking: 2, website: 'https://cam.ac.uk', description: 'A world-leading research institution celebrated for physics, mathematics, law, and natural sciences.' },
  { name: 'Imperial College London', slug: 'imperial-college-london', location: 'London, England', country: 'UK', established: 1907, ranking: 3, website: 'https://imperial.ac.uk', description: 'A specialist science, engineering, medicine and business university in the heart of London.' },
  { name: 'University College London', slug: 'university-college-london', location: 'London, England', country: 'UK', established: 1826, ranking: 4, website: 'https://ucl.ac.uk', description: 'A multidisciplinary global university known for architecture, law, economics and health sciences.' },
  { name: 'University of Edinburgh', slug: 'university-of-edinburgh', location: 'Edinburgh, Scotland', country: 'UK', established: 1583, ranking: 5, website: 'https://ed.ac.uk', description: 'Scotland\'s ancient university and a leader in informatics, medicine, and social sciences.' },
  { name: 'University of Manchester', slug: 'university-of-manchester', location: 'Manchester, England', country: 'UK', established: 1824, ranking: 6, website: 'https://manchester.ac.uk', description: 'A Russell Group university with strengths in business, engineering, and life sciences.' },
  { name: 'King\'s College London', slug: 'kings-college-london', location: 'London, England', country: 'UK', established: 1829, ranking: 7, website: 'https://kcl.ac.uk', description: 'A leading research university with superb strengths in law, health sciences, and humanities.' },
  { name: 'University of Bristol', slug: 'university-of-bristol', location: 'Bristol, England', country: 'UK', established: 1909, ranking: 8, website: 'https://bristol.ac.uk', description: 'A red-brick research university strong in engineering, law, and social sciences.' },
  { name: 'University of Warwick', slug: 'university-of-warwick', location: 'Coventry, England', country: 'UK', established: 1965, ranking: 9, website: 'https://warwick.ac.uk', description: 'Renowned for its business school, mathematics, and computer science programmes.' },
  { name: 'University of Leeds', slug: 'university-of-leeds', location: 'Leeds, England', country: 'UK', established: 1904, ranking: 10, website: 'https://leeds.ac.uk', description: 'A Russell Group university with broad strengths including law, business, and engineering.' },

  // ── USA ──────────────────────────────────────────────────────────────────
  { name: 'University of Southern California', slug: 'usc', location: 'Los Angeles, CA, USA', country: 'USA', established: 1880, ranking: 28, website: 'https://usc.edu', description: 'A leading private research university with renowned engineering and computer science programs.' },
  { name: 'Coastal Carolina University', slug: 'coastal-carolina-university', location: 'Conway, SC, USA', country: 'USA', established: 1954, ranking: 50, website: 'https://coastal.edu', description: 'A dynamic public university offering a wide range of undergraduate and graduate programs.' },
  { name: 'University of Virginia\'s College at Wise', slug: 'uva-wise', location: 'Wise, VA, USA', country: 'USA', established: 1954, ranking: 60, website: 'https://uvawise.edu', description: 'A public liberal arts college associated with the University of Virginia.' },
  { name: 'Abilene Christian University', slug: 'abilene-christian-university', location: 'Abilene, TX, USA', country: 'USA', established: 1906, ranking: 70, website: 'https://acu.edu', description: 'A private university known for its commitment to academic excellence and Christian values.' },
  { name: 'Eastern Oregon University', slug: 'eastern-oregon-university', location: 'La Grande, OR, USA', country: 'USA', established: 1929, ranking: 80, website: 'https://eou.edu', description: 'Oregon\'s rural university serving students across the region with robust academic programs.' },
  { name: 'Massachusetts Institute of Technology', slug: 'mit', location: 'Cambridge, MA, USA', country: 'USA', established: 1861, ranking: 11, website: 'https://mit.edu', description: 'The world\'s foremost science and technology university, home of course CS50 and countless engineering breakthroughs.' },
  { name: 'Harvard University', slug: 'harvard-university', location: 'Cambridge, MA, USA', country: 'USA', established: 1636, ranking: 12, website: 'https://harvard.edu', description: 'America\'s oldest university, globally recognised for law, medicine, business, and economics.' },
  { name: 'Stanford University', slug: 'stanford-university', location: 'Stanford, CA, USA', country: 'USA', established: 1885, ranking: 13, website: 'https://stanford.edu', description: 'Silicon Valley\'s flagship university acclaimed for entrepreneurship, engineering, and computer science.' },
  { name: 'University of California, Los Angeles', slug: 'ucla', location: 'Los Angeles, CA, USA', country: 'USA', established: 1919, ranking: 14, website: 'https://ucla.edu', description: 'A world-class public research university with strong programmes in medicine, law, and the arts.' },
  { name: 'New York University', slug: 'nyu', location: 'New York, NY, USA', country: 'USA', established: 1831, ranking: 15, website: 'https://nyu.edu', description: 'A global university in the heart of New York City, known for business, law, and media studies.' },
  { name: 'Columbia University', slug: 'columbia-university', location: 'New York, NY, USA', country: 'USA', established: 1754, ranking: 16, website: 'https://columbia.edu', description: 'An Ivy League research university renowned for journalism, law, and political science.' },
  { name: 'University of Michigan', slug: 'university-of-michigan', location: 'Ann Arbor, MI, USA', country: 'USA', established: 1817, ranking: 17, website: 'https://umich.edu', description: 'One of America\'s great public research universities with outstanding business, engineering, and medicine schools.' },
  { name: 'University of Texas at Austin', slug: 'ut-austin', location: 'Austin, TX, USA', country: 'USA', established: 1883, ranking: 18, website: 'https://utexas.edu', description: 'A flagship public research university with leading programmes in business, law, and computer science.' },

  // ── Canada ───────────────────────────────────────────────────────────────
  { name: 'University of Toronto', slug: 'university-of-toronto', location: 'Toronto, ON, Canada', country: 'Canada', established: 1827, ranking: 19, website: 'https://utoronto.ca', description: 'Canada\'s leading research university with globally respected programmes in medicine, law, and engineering.' },
  { name: 'University of British Columbia', slug: 'ubc', location: 'Vancouver, BC, Canada', country: 'Canada', established: 1908, ranking: 20, website: 'https://ubc.ca', description: 'A top-ranked Canadian public university known for its programmes in science, business, and social sciences.' },
  { name: 'McGill University', slug: 'mcgill-university', location: 'Montreal, QC, Canada', country: 'Canada', established: 1821, ranking: 21, website: 'https://mcgill.ca', description: 'Canada\'s most international university, celebrated for medicine, law, and natural sciences.' },

  // ── Australia ──────────────────────────────────────────────────────────
  { name: 'University of Melbourne', slug: 'university-of-melbourne', location: 'Melbourne, VIC, Australia', country: 'Australia', established: 1853, ranking: 22, website: 'https://unimelb.edu.au', description: 'Australia\'s leading research university with excellence in business, medicine, and law.' },
  { name: 'Australian National University', slug: 'anu', location: 'Canberra, ACT, Australia', country: 'Australia', established: 1946, ranking: 23, website: 'https://anu.edu.au', description: 'Australia\'s national research university renowned for politics, law, and policy sciences.' },
  { name: 'University of Sydney', slug: 'university-of-sydney', location: 'Sydney, NSW, Australia', country: 'Australia', established: 1850, ranking: 24, website: 'https://sydney.edu.au', description: 'Australia\'s first university with strong programmes in engineering, business, and health sciences.' },
  { name: 'University of New South Wales', slug: 'unsw', location: 'Sydney, NSW, Australia', country: 'Australia', established: 1949, ranking: 25, website: 'https://unsw.edu.au', description: 'A leading Australian research university known for engineering, computer science, and business.' },
]

// ─────────────────────────────────────────────────────────────────────────────
// COURSES — worldwide with real course codes
// ─────────────────────────────────────────────────────────────────────────────
export const courses = [
  // ── UK — Oxford ──────────────────────────────────────────────────────────
  { code: 'OXLAW101', title: 'Introduction to Contract Law', description: 'Foundational contract law covering offer, acceptance, consideration, intention, capacity, and remedies. Essential for all LLB students.', level: 'Undergraduate', credits: 20, outcomes: 'Analyse contract formation|Apply breach and remedy principles|Evaluate case law critically', universitySlug: 'university-of-oxford', subjectSlug: 'law' },
  { code: 'OXCS201', title: 'Algorithms & Data Structures', description: 'Core algorithms including sorting, searching, graph traversal, dynamic programming and complexity analysis.', level: 'Undergraduate', credits: 20, outcomes: 'Implement key algorithms in Python|Analyse time complexity|Solve algorithmic problems', universitySlug: 'university-of-oxford', subjectSlug: 'computer-science' },
  { code: 'OXECON301', title: 'Macroeconomics', description: 'National income, monetary policy, fiscal policy, inflation, unemployment, and open-economy models.', level: 'Undergraduate', credits: 20, outcomes: 'Apply IS-LM models|Critique monetary policy|Write economic policy reports', universitySlug: 'university-of-oxford', subjectSlug: 'economics' },

  // ── UK — Cambridge ────────────────────────────────────────────────────────
  { code: 'CAMMATH101', title: 'Calculus and Analysis', description: 'Real analysis, limits, continuity, differentiation, and integration. Rigorous mathematical reasoning for Part IA of the Tripos.', level: 'Undergraduate', credits: 24, outcomes: 'Prove analysis theorems|Apply integration techniques|Understand series convergence', universitySlug: 'university-of-cambridge', subjectSlug: 'mathematics' },
  { code: 'CAMCS310', title: 'Machine Learning', description: 'Supervised and unsupervised learning, neural networks, support vector machines, and Bayesian methods.', level: 'Postgraduate', credits: 20, outcomes: 'Build ML pipelines in Python|Train neural networks|Evaluate model performance', universitySlug: 'university-of-cambridge', subjectSlug: 'data-science' },
  { code: 'CAMLAW201', title: 'Criminal Law', description: 'Elements of criminal offences including actus reus, mens rea, defences, and sentencing principles.', level: 'Undergraduate', credits: 20, outcomes: 'Identify criminal liability|Construct legal arguments|Apply defences in scenarios', universitySlug: 'university-of-cambridge', subjectSlug: 'law' },

  // ── UK — Imperial ─────────────────────────────────────────────────────────
  { code: 'EE306', title: 'Power Electronics', description: 'Converter topologies, PWM techniques, motor drives, and renewable energy integration.', level: 'Undergraduate', credits: 20, outcomes: 'Design DC-DC converters|Simulate power circuits|Apply control strategies', universitySlug: 'imperial-college-london', subjectSlug: 'engineering' },
  { code: 'BIOE401', title: 'Biomedical Engineering', description: 'Medical imaging, biomechanics, tissue engineering, and biosignal processing.', level: 'Postgraduate', credits: 20, outcomes: 'Analyse medical signals|Design biomedical devices|Write research reports', universitySlug: 'imperial-college-london', subjectSlug: 'engineering' },

  // ── UK — UCL ──────────────────────────────────────────────────────────────
  { code: 'COMP0005', title: 'Algorithms', description: 'Algorithmic complexity, divide-and-conquer, greedy algorithms, dynamic programming, and NP-completeness.', level: 'Undergraduate', credits: 15, outcomes: 'Analyse algorithms formally|Implement solutions in Python|Prove correctness', universitySlug: 'university-college-london', subjectSlug: 'computer-science' },
  { code: 'ECON2001', title: 'Intermediate Microeconomics', description: 'Consumer and producer theory, market structure, game theory, and welfare economics.', level: 'Undergraduate', credits: 15, outcomes: 'Apply utility maximisation|Analyse market failures|Solve game-theory problems', universitySlug: 'university-college-london', subjectSlug: 'economics' },
  { code: 'NURS2020', title: 'Adult Nursing Practice', description: 'Evidence-based nursing care, clinical assessment, medicines management, and professional ethics.', level: 'Undergraduate', credits: 20, outcomes: 'Conduct patient assessments|Apply medication protocols|Reflect on clinical practice', universitySlug: 'university-college-london', subjectSlug: 'nursing' },

  // ── UK — Edinburgh ───────────────────────────────────────────────────────
  { code: 'INFR08025', title: 'Introduction to Databases', description: 'Relational model, SQL, normalisation, transactions, and database design.', level: 'Undergraduate', credits: 20, outcomes: 'Design relational schemas|Write complex SQL queries|Apply normalisation', universitySlug: 'university-of-edinburgh', subjectSlug: 'computer-science' },
  { code: 'PSYC08001', title: 'Cognitive Psychology', description: 'Attention, memory, language, problem-solving, and decision-making from a cognitive science perspective.', level: 'Undergraduate', credits: 20, outcomes: 'Evaluate cognitive theories|Design experiments|Interpret research findings', universitySlug: 'university-of-edinburgh', subjectSlug: 'psychology' },

  // ── UK — Manchester ───────────────────────────────────────────────────────
  { code: 'BMAN10001', title: 'Principles of Finance', description: 'Time value of money, risk and return, portfolio theory, capital structure, and equity valuation.', level: 'Undergraduate', credits: 20, outcomes: 'Calculate NPV and IRR|Apply CAPM model|Produce financial analysis reports', universitySlug: 'university-of-manchester', subjectSlug: 'accounting-finance' },
  { code: 'MCEL10001', title: 'Electrical Circuits', description: 'Circuit analysis, AC/DC theory, Thevenin and Norton theorems, and frequency response.', level: 'Undergraduate', credits: 20, outcomes: 'Analyse complex circuits|Apply network theorems|Use circuit simulation tools', universitySlug: 'university-of-manchester', subjectSlug: 'engineering' },

  // ── UK — King's ─────────────────────────────────────────────────────────
  { code: 'KC5H3210', title: 'Healthcare Management', description: 'NHS structure, health policy, leadership, quality improvement, and patient safety.', level: 'Postgraduate', credits: 30, outcomes: 'Analyse health policy|Lead quality improvement|Write strategic reports', universitySlug: 'kings-college-london', subjectSlug: 'medicine' },

  // ── UK — Warwick ─────────────────────────────────────────────────────────
  { code: 'WBS302', title: 'Strategic Management', description: 'Competitive strategy frameworks including Porter\'s Five Forces, SWOT, VRIN, and Blue Ocean strategy.', level: 'Undergraduate', credits: 20, outcomes: 'Apply strategic frameworks|Write business case studies|Present strategic proposals', universitySlug: 'university-of-warwick', subjectSlug: 'business-management' },
  { code: 'MA207', title: 'Linear Algebra', description: 'Vector spaces, linear transformations, matrices, eigenvalues, and inner product spaces.', level: 'Undergraduate', credits: 20, outcomes: 'Prove linear algebra results|Apply matrix operations|Solve eigenvalue problems', universitySlug: 'university-of-warwick', subjectSlug: 'mathematics' },

  // ── USA — MIT ────────────────────────────────────────────────────────────
  { code: 'CS50', title: 'Introduction to Computer Science', description: 'Harvard/MIT\'s legendary intro CS course covering C, Python, SQL, web development, and problem-solving from scratch.', level: 'Undergraduate', credits: 12, outcomes: 'Write programs in C and Python|Build web applications|Understand computational thinking', universitySlug: 'mit', subjectSlug: 'computer-science' },
  { code: '6.006', title: 'Introduction to Algorithms', description: 'Sorting, searching, hashing, graph algorithms, dynamic programming, and shortest paths.', level: 'Undergraduate', credits: 12, outcomes: 'Analyse algorithm complexity|Implement graph algorithms|Apply dynamic programming', universitySlug: 'mit', subjectSlug: 'computer-science' },
  { code: '18.06', title: 'Linear Algebra (Strang)', description: 'MIT\'s famed linear algebra course covering matrices, vector spaces, eigenvalues, and SVD.', level: 'Undergraduate', credits: 12, outcomes: 'Apply matrix decompositions|Understand least squares|Solve systems of equations', universitySlug: 'mit', subjectSlug: 'mathematics' },
  { code: '6.867', title: 'Machine Learning', description: 'Supervised learning, kernel methods, probabilistic models, and deep learning foundations.', level: 'Postgraduate', credits: 12, outcomes: 'Implement ML algorithms|Train neural networks|Evaluate model performance', universitySlug: 'mit', subjectSlug: 'data-science' },
  { code: '2.001', title: 'Mechanics & Materials', description: 'Stress, strain, elasticity, structural analysis, and material properties for engineers.', level: 'Undergraduate', credits: 12, outcomes: 'Analyse structural loads|Select engineering materials|Write lab reports', universitySlug: 'mit', subjectSlug: 'engineering' },

  // ── USA — Harvard ────────────────────────────────────────────────────────
  { code: 'ECON1010A', title: 'Principles of Economics', description: 'Microeconomic fundamentals including supply and demand, market equilibrium, consumer behaviour, and firm theory.', level: 'Undergraduate', credits: 4, outcomes: 'Apply micro models|Analyse market outcomes|Write economic essays', universitySlug: 'harvard-university', subjectSlug: 'economics' },
  { code: 'HLS101', title: 'Introduction to Law', description: 'American legal system, common law, statutory interpretation, constitutional law foundations, and legal reasoning.', level: 'Undergraduate', credits: 4, outcomes: 'Analyse legal precedents|Construct legal arguments|Draft case briefs', universitySlug: 'harvard-university', subjectSlug: 'law' },
  { code: 'PSY1', title: 'Introduction to Psychology', description: 'Neuroscience, development, memory, social psychology, psychopathology, and clinical approaches.', level: 'Undergraduate', credits: 4, outcomes: 'Apply psychological theories|Design study experiments|Write APA-format reports', universitySlug: 'harvard-university', subjectSlug: 'psychology' },
  { code: 'STAT110', title: 'Probability', description: 'Probability theory, random variables, distributions, Markov chains, and statistical inference.', level: 'Undergraduate', credits: 4, outcomes: 'Calculate probabilities|Apply Bayes theorem|Model stochastic processes', universitySlug: 'harvard-university', subjectSlug: 'mathematics' },

  // ── USA — Stanford ───────────────────────────────────────────────────────
  { code: 'CS101', title: 'Introduction to Computing Principles', description: 'Computational thinking, data representation, algorithms, programming in JavaScript, and societal impacts.', level: 'Undergraduate', credits: 5, outcomes: 'Write JavaScript programs|Understand data encoding|Analyse algorithm efficiency', universitySlug: 'stanford-university', subjectSlug: 'computer-science' },
  { code: 'CS229', title: 'Machine Learning (Ng)', description: 'Andrew Ng\'s renowned ML course: regression, classification, neural networks, SVMs, and unsupervised learning.', level: 'Postgraduate', credits: 4, outcomes: 'Implement gradient descent|Build neural networks|Apply dimensionality reduction', universitySlug: 'stanford-university', subjectSlug: 'data-science' },
  { code: 'MS&E211', title: 'Introduction to Optimization', description: 'Linear programming, simplex method, duality, integer programming, and convex optimisation.', level: 'Undergraduate', credits: 4, outcomes: 'Formulate LP problems|Apply simplex method|Interpret dual solutions', universitySlug: 'stanford-university', subjectSlug: 'mathematics' },
  { code: 'GSB501', title: 'Finance I', description: 'Corporate finance, valuation, capital budgeting, risk and return, options, and financial strategy.', level: 'Postgraduate', credits: 4, outcomes: 'Value companies using DCF|Apply options pricing|Analyse capital structure', universitySlug: 'stanford-university', subjectSlug: 'accounting-finance' },

  // ── USA — UCLA ────────────────────────────────────────────────────────────
  { code: 'COM SCI31', title: 'Introduction to Computer Science I', description: 'Problem-solving methodology, Python programming, data types, control flow, functions, and recursion.', level: 'Undergraduate', credits: 4, outcomes: 'Write Python programs|Apply recursion|Debug software systematically', universitySlug: 'ucla', subjectSlug: 'computer-science' },
  { code: 'MGMT201', title: 'Principles of Management', description: 'Planning, organising, leading, and controlling in organisations. Contemporary management theories.', level: 'Undergraduate', credits: 4, outcomes: 'Apply management theories|Analyse organisational behaviour|Write management reports', universitySlug: 'ucla', subjectSlug: 'business-management' },
  { code: 'PSYCH10', title: 'Introduction to Psychology', description: 'Biological bases of behaviour, sensation, perception, learning, memory, motivation, and personality.', level: 'Undergraduate', credits: 5, outcomes: 'Explain psychological phenomena|Evaluate research studies|Apply critical thinking', universitySlug: 'ucla', subjectSlug: 'psychology' },

  // ── USA — NYU ────────────────────────────────────────────────────────────
  { code: 'LAW2101', title: 'Business Law', description: 'Contract law, torts, agency, business organisations, intellectual property, and employment law.', level: 'Undergraduate', credits: 4, outcomes: 'Identify legal issues in business|Draft contract clauses|Apply business law rules', universitySlug: 'nyu', subjectSlug: 'law' },
  { code: 'ECON101', title: 'Principles of Microeconomics', description: 'Supply and demand, elasticity, utility, firm behaviour, competition, and market structures.', level: 'Undergraduate', credits: 4, outcomes: 'Graph supply and demand|Calculate elasticities|Analyse market structures', universitySlug: 'nyu', subjectSlug: 'economics' },
  { code: 'MKT101', title: 'Principles of Marketing', description: 'Marketing mix, consumer behaviour, segmentation, targeting, positioning, and digital marketing.', level: 'Undergraduate', credits: 4, outcomes: 'Develop marketing plans|Analyse consumer data|Write IMC campaigns', universitySlug: 'nyu', subjectSlug: 'marketing' },

  // ── USA — Columbia ────────────────────────────────────────────────────────
  { code: 'COMS4771', title: 'Machine Learning (Columbia)', description: 'Probability, statistical learning theory, linear models, kernel methods, and neural networks.', level: 'Postgraduate', credits: 3, outcomes: 'Derive learning algorithms|Implement classification models|Evaluate with cross-validation', universitySlug: 'columbia-university', subjectSlug: 'data-science' },
  { code: 'BUS101', title: 'Introduction to Business', description: 'Business environment, entrepreneurship, management functions, marketing, finance, and ethics.', level: 'Undergraduate', credits: 3, outcomes: 'Describe business functions|Analyse case studies|Produce a simple business plan', universitySlug: 'columbia-university', subjectSlug: 'business-management' },

  // ── USA — Michigan ─────────────────────────────────────────────────────
  { code: 'EECS281', title: 'Data Structures and Algorithms', description: 'Arrays, linked lists, trees, hash tables, graphs, sorting algorithms, and algorithmic analysis.', level: 'Undergraduate', credits: 4, outcomes: 'Choose appropriate data structures|Implement graph algorithms|Optimise program performance', universitySlug: 'university-of-michigan', subjectSlug: 'computer-science' },
  { code: 'ACC300', title: 'Financial Accounting', description: 'Accounting cycle, financial statements, GAAP principles, assets, liabilities, and equity.', level: 'Undergraduate', credits: 3, outcomes: 'Prepare financial statements|Apply debits and credits|Interpret balance sheets', universitySlug: 'university-of-michigan', subjectSlug: 'accounting-finance' },

  // ── USA — UT Austin ───────────────────────────────────────────────────────
  { code: 'CS312', title: 'Software Engineering', description: 'Requirements engineering, software design patterns, testing, agile methods, and version control.', level: 'Undergraduate', credits: 3, outcomes: 'Apply UML diagrams|Write unit tests|Follow agile workflows', universitySlug: 'ut-austin', subjectSlug: 'computer-science' },
  { code: 'MAN320F', title: 'Foundations of Business', description: 'Business ethics, strategic planning, financial analysis, human resources, and operations management.', level: 'Undergraduate', credits: 3, outcomes: 'Analyse business cases|Apply strategic tools|Write business reports', universitySlug: 'ut-austin', subjectSlug: 'business-management' },

  // ── Canada — Toronto ──────────────────────────────────────────────────────
  { code: 'CSC148H1', title: 'Introduction to Computer Science (Toronto)', description: 'Object-oriented programming in Python, recursion, linked lists, trees, and algorithm analysis.', level: 'Undergraduate', credits: 0.5, outcomes: 'Write OOP Python code|Implement recursive algorithms|Analyse program efficiency', universitySlug: 'university-of-toronto', subjectSlug: 'computer-science' },
  { code: 'ECO101H1', title: 'Principles of Microeconomics (Toronto)', description: 'Consumer choice, firm theory, market structures, externalities, and public goods.', level: 'Undergraduate', credits: 0.5, outcomes: 'Apply demand-supply models|Analyse market failures|Write economic essays', universitySlug: 'university-of-toronto', subjectSlug: 'economics' },
  { code: 'NUR202', title: 'Foundations of Nursing Practice', description: 'Patient-centred care, clinical reasoning, health assessment, and evidence-based practice.', level: 'Undergraduate', credits: 0.5, outcomes: 'Conduct nursing assessments|Apply clinical reasoning|Reflect on nursing ethics', universitySlug: 'university-of-toronto', subjectSlug: 'nursing' },

  // ── Canada — UBC ──────────────────────────────────────────────────────────
  { code: 'CPSC110', title: 'Computation, Programs, and Programming', description: 'Systematic program design in Racket, functions, recursion, lists, and higher-order functions.', level: 'Undergraduate', credits: 4, outcomes: 'Design programs systematically|Apply functional programming|Test programs rigorously', universitySlug: 'ubc', subjectSlug: 'computer-science' },
  { code: 'COMM101', title: 'Introduction to Commerce', description: 'Business organisation, marketing, accounting, finance, operations, and the Canadian business environment.', level: 'Undergraduate', credits: 3, outcomes: 'Understand business functions|Analyse case studies|Present business ideas', universitySlug: 'ubc', subjectSlug: 'business-management' },

  // ── Canada — McGill ───────────────────────────────────────────────────────
  { code: 'COMP250', title: 'Introduction to Computer Science (McGill)', description: 'Mathematical tools, Java programming, data structures, sorting, and computational complexity.', level: 'Undergraduate', credits: 3, outcomes: 'Write Java programs|Implement data structures|Prove algorithm correctness', universitySlug: 'mcgill-university', subjectSlug: 'computer-science' },
  { code: 'MGCR293', title: 'Accounting for Management Decisions', description: 'Financial and managerial accounting principles for business decision-making.', level: 'Undergraduate', credits: 3, outcomes: 'Prepare management accounts|Perform CVP analysis|Support business decisions', universitySlug: 'mcgill-university', subjectSlug: 'accounting-finance' },

  // ── Australia — Melbourne ─────────────────────────────────────────────────
  { code: 'COMP10001', title: 'Foundations of Computing', description: 'Computational thinking, Python programming, problem decomposition, and data analysis.', level: 'Undergraduate', credits: 12.5, outcomes: 'Write Python scripts|Analyse datasets|Solve computational problems', universitySlug: 'university-of-melbourne', subjectSlug: 'computer-science' },
  { code: 'MGMT10002', title: 'Principles of Management (Melbourne)', description: 'Management theory, leadership, organisational design, HRM, and strategic management.', level: 'Undergraduate', credits: 12.5, outcomes: 'Apply management frameworks|Analyse organisations|Write management assignments', universitySlug: 'university-of-melbourne', subjectSlug: 'business-management' },
  { code: 'MKTG90027', title: 'Marketing Management', description: 'Market analysis, consumer behaviour, STP, marketing mix, and digital marketing strategy.', level: 'Postgraduate', credits: 12.5, outcomes: 'Develop marketing strategy|Analyse consumer behaviour|Present marketing plans', universitySlug: 'university-of-melbourne', subjectSlug: 'marketing' },

  // ── Australia — ANU ───────────────────────────────────────────────────────
  { code: 'COMP1100', title: 'Programming as Problem Solving', description: 'Problem solving through functional programming in Haskell, recursion, and type systems.', level: 'Undergraduate', credits: 6, outcomes: 'Write Haskell programs|Apply functional techniques|Design type-safe code', universitySlug: 'anu', subjectSlug: 'computer-science' },
  { code: 'LAWS1201', title: 'Foundations of Australian Law', description: 'Australian legal system, common law, statute law, constitutional framework, and legal reasoning.', level: 'Undergraduate', credits: 6, outcomes: 'Navigate legal sources|Construct legal arguments|Write legal memoranda', universitySlug: 'anu', subjectSlug: 'law' },

  // ── Australia — Sydney ────────────────────────────────────────────────────
  { code: 'INFO1110', title: 'Introduction to Programming', description: 'Java programming fundamentals, OOP, debugging, testing, and software development practices.', level: 'Undergraduate', credits: 6, outcomes: 'Write Java programs|Apply OOP principles|Test and debug software', universitySlug: 'university-of-sydney', subjectSlug: 'computer-science' },
  { code: 'BUSS1044', title: 'Business and Economic Statistics', description: 'Descriptive statistics, probability, inference, regression analysis, and business data visualisation.', level: 'Undergraduate', credits: 6, outcomes: 'Apply statistical tests|Build regression models|Interpret business data', universitySlug: 'university-of-sydney', subjectSlug: 'mathematics' },

  // ── Australia — UNSW ─────────────────────────────────────────────────────
  { code: 'COMP1511', title: 'Programming Fundamentals (UNSW)', description: 'C programming, problem solving, arrays, pointers, data structures, and software practices.', level: 'Undergraduate', credits: 6, outcomes: 'Write C programs|Manage memory safely|Implement linked lists and arrays', universitySlug: 'unsw', subjectSlug: 'computer-science' },
  { code: 'ACCT1501', title: 'Accounting & Financial Management', description: 'Accounting conceptual framework, financial statements, ratio analysis, and management accounting.', level: 'Undergraduate', credits: 6, outcomes: 'Prepare financial statements|Analyse ratios|Apply management accounting techniques', universitySlug: 'unsw', subjectSlug: 'accounting-finance' },
  { code: 'MKTG1021', title: 'Marketing Principles (UNSW)', description: 'Marketing philosophy, environment scanning, buyer behaviour, and the extended marketing mix.', level: 'Undergraduate', credits: 6, outcomes: 'Conduct market audits|Apply marketing mix|Write campaign briefs', universitySlug: 'unsw', subjectSlug: 'marketing' },

  // ── USC ──────────────────────────────────────────────────────────────────
  { code: 'CSC104L', title: 'Data Structures and Algorithms', description: 'Lists, stacks, queues, trees, hash tables, and algorithm analysis.', level: 'Undergraduate', credits: 4, outcomes: 'Implement data structures|Analyze time complexity|Write robust programs', universitySlug: 'usc', subjectSlug: 'computer-science' },
  { code: 'CS350', title: 'Fundamentals of Operating Systems', description: 'Core operating system concepts including process management, memory management, and file systems.', level: 'Undergraduate', credits: 4, outcomes: 'Understand process management|Analyze file systems|Write OS-level code', universitySlug: 'usc', subjectSlug: 'computer-science' },
  { code: 'CS430', title: 'Computer and Network Security', description: 'Security concepts, threats, vulnerabilities, risk management, and network security strategies.', level: 'Undergraduate', credits: 4, outcomes: 'Identify security threats|Apply risk management|Secure network protocols', universitySlug: 'usc', subjectSlug: 'computer-science' },
  { code: 'CS450', title: 'Introduction to Computer Networks', description: 'OSI model, TCP/IP, routing, and network protocols.', level: 'Undergraduate', credits: 4, outcomes: 'Understand OSI model|Configure TCP/IP networks|Implement routing protocols', universitySlug: 'usc', subjectSlug: 'computer-science' },
  { code: 'CS352L', title: 'Computer Organization and Architecture', description: 'Processor, control and memory design, computer arithmetic, and I/O systems.', level: 'Undergraduate', credits: 4, outcomes: 'Analyze processor design|Understand memory hierarchy|Interface with I/O systems', universitySlug: 'usc', subjectSlug: 'computer-science' },
  { code: 'CS475', title: 'Theory of Computation', description: 'Structured grammars, finite automata, push-down automata, Turing machines, and computability.', level: 'Undergraduate', credits: 4, outcomes: 'Construct automata|Analyze Turing machines|Understand computational limits', universitySlug: 'usc', subjectSlug: 'computer-science' },

  // ── Coastal Carolina University ──────────────────────────────────────────
  { code: 'CSCI220', title: 'Data Structures', description: 'Data and abstract data types; programming principles, lists, dynamic memory allocation, stacks, queues, trees, graphs, and recursion.', level: 'Undergraduate', credits: 3, outcomes: 'Implement dynamic memory allocation|Apply recursive logic|Design abstract data types', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI230', title: 'Object-Oriented Programming', description: 'Classes, objects, inheritance, and polymorphism.', level: 'Undergraduate', credits: 3, outcomes: 'Apply inheritance concepts|Understand polymorphism|Design robust objects', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI356', title: 'Operating Systems', description: 'Concepts behind operating system design: resource management, processes, process management, file systems, and system calls.', level: 'Undergraduate', credits: 3, outcomes: 'Manage system resources|Implement system calls|Understand file system architecture', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI380', title: 'Introduction to the Analysis of Algorithms', description: 'Sorting and searching; recursion; analysis of complexity; algorithm paradigms; NP-complete problems; complexity metrics.', level: 'Undergraduate', credits: 3, outcomes: 'Analyze NP-complete problems|Evaluate complexity metrics|Implement sorting algorithms', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI350', title: 'Organization of Programming Languages', description: 'Survey of contemporary languages, compiler construction techniques, parsing, formal grammars, and virtual machines.', level: 'Undergraduate', credits: 3, outcomes: 'Build formal grammars|Understand compiler techniques|Survey contemporary programming paradigms', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI385', title: 'Introduction to Information Systems Security', description: 'Fundamentals of cybersecurity, cyber-attacks, software vulnerabilities, malware, and security policies.', level: 'Undergraduate', credits: 3, outcomes: 'Develop security policies|Analyze software vulnerabilities|Mitigate cyber-attacks', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI386', title: 'Offensive Security', description: 'Introduction to the full penetration test life cycle in an ethical context.', level: 'Undergraduate', credits: 3, outcomes: 'Conduct ethical pen tests|Identify network vulnerabilities|Document security flaws', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI434', title: 'Digital Forensics', description: 'Computer forensic investigation principles and techniques, data and evidence collection, and incident response.', level: 'Undergraduate', credits: 3, outcomes: 'Collect digital evidence|Respond to security incidents|Follow forensic investigation principles', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI408', title: 'Cryptography', description: 'Foundational principles of cryptography, symmetric/asymmetric encryption, hashing algorithms, and digital signatures.', level: 'Undergraduate', credits: 3, outcomes: 'Implement hashing algorithms|Understand asymmetric encryption|Generate digital signatures', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI225', title: 'Introduction to Relational Database and SQL', description: 'Evolution of data models, relational algebra, SQL, and database design.', level: 'Undergraduate', credits: 3, outcomes: 'Write complex SQL queries|Design database architecture|Apply relational algebra', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI270', title: 'Data Communication Systems and Networks', description: 'OSI model, TCP/IP, routing, and network protocols.', level: 'Undergraduate', credits: 3, outcomes: 'Analyze network layers|Configure routing protocols|Understand data communication', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI480', title: 'Introduction to Artificial Intelligence', description: 'Comprehensive introduction to the field of artificially intelligent computer-based systems.', level: 'Undergraduate', credits: 3, outcomes: 'Design AI systems|Implement search algorithms|Understand knowledge representation', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI484', title: 'Machine Learning', description: 'Supervised and unsupervised learning, modeling and prediction, and formulation of learning problems.', level: 'Undergraduate', credits: 3, outcomes: 'Formulate learning models|Implement predictive algorithms|Evaluate model accuracy', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI204', title: 'Programming in JavaScript', description: 'Web programming technologies including JavaScript, CSS, and interactive application development.', level: 'Undergraduate', credits: 3, outcomes: 'Develop interactive applications|Write modern JavaScript|Apply CSS styling', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI207', title: 'Programming in C++', description: 'C++ syntax and programming structures including pointers, arrays, and classes.', level: 'Undergraduate', credits: 3, outcomes: 'Manage memory with pointers|Design C++ classes|Work with arrays safely', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI209', title: 'Programming in Java', description: 'Java language syntax, classes, applets, multithreading, and user interfaces.', level: 'Undergraduate', credits: 3, outcomes: 'Develop Java user interfaces|Implement multithreading|Design scalable Java classes', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI444', title: 'Human Computer Interaction', description: 'User-centered GUI development, iterative design process, prototyping, and user testing.', level: 'Undergraduate', credits: 3, outcomes: 'Create user-centered designs|Prototype GUIs|Perform iterative testing', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI445', title: 'Image Processing and Analysis', description: 'Traditional and current approaches to pattern recognition in images and signals.', level: 'Undergraduate', credits: 3, outcomes: 'Process image data|Implement pattern recognition|Analyze visual signals', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI455', title: 'Data Science and Analytics', description: 'Data exploration, statistical methods, and analytical techniques for large datasets.', level: 'Undergraduate', credits: 3, outcomes: 'Explore large datasets|Apply statistical techniques|Visualize analytical findings', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI485', title: 'Introduction to Robotics', description: 'Programming of artificially intelligent robots: sensing, navigation, and path planning.', level: 'Undergraduate', credits: 3, outcomes: 'Program robot navigation|Implement path planning algorithms|Process sensory data', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI101', title: 'Introduction to the Internet and World Wide Web', description: 'Basic concepts of internet technologies and web fundamentals.', level: 'Undergraduate', credits: 3, outcomes: 'Understand web architectures|Build basic web pages|Explore internet fundamentals', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI130', title: 'Introduction to Computer Science', description: 'Foundational concepts of computer science and programming.', level: 'Undergraduate', credits: 3, outcomes: 'Understand foundational concepts|Write basic level programs|Develop logical reasoning', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI170', title: 'Ethics in Computer Science', description: 'Professional and ethical issues in computing and technology.', level: 'Undergraduate', credits: 1, outcomes: 'Recognize ethical dilemmas|Analyze professional issues|Understand technology impacts', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI330', title: 'Systems Analysis & Software Engineering', description: 'Development of a total system concept: project planning, requirements analysis, system design, and testing.', level: 'Undergraduate', credits: 3, outcomes: 'Analyze software requirements|Design complete systems|Execute project planning', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },
  { code: 'CSCI390', title: 'Theory of Computation', description: 'Structured grammars, finite automata, push-down automata, Turing machines, and computability.', level: 'Undergraduate', credits: 3, outcomes: 'Build state machines|Understand grammar structures|Evaluate computational limits', universitySlug: 'coastal-carolina-university', subjectSlug: 'computer-science' },

  // ── UVA Wise ─────────────────────────────────────────────────────────────
  { code: 'CSC2180', title: 'Data Structures', description: 'Data and abstract data types; programming principles, lists, dynamic memory allocation, stacks, queues, trees, graphs, and recursion.', level: 'Undergraduate', credits: 4, outcomes: 'Implement data structures|Apply recursive problem solving|Optimize dynamic allocation', universitySlug: 'uva-wise', subjectSlug: 'computer-science' },
  { code: 'CSC3180', title: 'Introduction to Algorithms', description: 'Sorting and searching; recursion; analysis of complexity; algorithm paradigms; NP-complete problems; complexity metrics.', level: 'Undergraduate', credits: 3, outcomes: 'Solve NP-complete challenges|Implement efficient sorting|Analyze time-space trade-offs', universitySlug: 'uva-wise', subjectSlug: 'computer-science' },
  { code: 'CSC4200', title: 'Programming Languages', description: 'Survey of contemporary languages, compiler construction techniques, parsing, formal grammars, and virtual machines.', level: 'Undergraduate', credits: 3, outcomes: 'Evaluate language paradigms|Understand parsing algorithms|Examine virtual machine design', universitySlug: 'uva-wise', subjectSlug: 'computer-science' },
  { code: 'CSC4280', title: 'Cybersecurity', description: 'Fundamentals of cybersecurity, cyber-attacks, software vulnerabilities and exploitation, malware, cryptography, and security policies.', level: 'Undergraduate', credits: 3, outcomes: 'Investigate software vulnerabilities|Implement basic cryptography|Explore defense mechanisms', universitySlug: 'uva-wise', subjectSlug: 'computer-science' },
  { code: 'CSC3400', title: 'Database Design & Applications', description: 'Relational model, SQL, database design, implementation, and manipulation.', level: 'Undergraduate', credits: 3, outcomes: 'Design normalized databases|Manipulate large SQL tables|Implement modern data models', universitySlug: 'uva-wise', subjectSlug: 'computer-science' },
  { code: 'CSC4150', title: 'Machine Learning & AI', description: 'Introduction to data exploration, coding, statistics, and visualization using Python and Jupyter.', level: 'Undergraduate', credits: 3, outcomes: 'Analyze data in Jupyter|Code learning algorithms|Visualize statistical results', universitySlug: 'uva-wise', subjectSlug: 'computer-science' },
  { code: 'CS3260', title: 'Introduction to Human Computer Interaction', description: 'User-centered GUI development, iterative design process, prototyping tools, and user testing.', level: 'Undergraduate', credits: 3, outcomes: 'Conduct usability tests|Prototype user interfaces|Refine interactive experiences', universitySlug: 'uva-wise', subjectSlug: 'computer-science' },

  // ── Abilene Christian University ─────────────────────────────────────────
  { code: 'CS230', title: 'Object-Oriented Programming', description: 'Classes, objects, inheritance, and polymorphism.', level: 'Undergraduate', credits: 3, outcomes: 'Write object-oriented code|Implement inheritance patterns|Design polymorphic systems', universitySlug: 'abilene-christian-university', subjectSlug: 'computer-science' },

  // ── Eastern Oregon University ────────────────────────────────────────────
  { code: 'CS360', title: 'Object-Oriented Programming with C++', description: 'Advanced object-oriented programming concepts using C++.', level: 'Undergraduate', credits: 4, outcomes: 'Master advanced C++ OOP|Optimize unmanaged memory|Apply structural design patterns', universitySlug: 'eastern-oregon-university', subjectSlug: 'computer-science' },
  { code: 'CS311', title: 'Operating Systems', description: 'Resource management, processes, process management, file design and allocation, system calls, and shell design.', level: 'Undergraduate', credits: 3, outcomes: 'Develop custom shells|Handle system concurrency|Explore resource allocation', universitySlug: 'eastern-oregon-university', subjectSlug: 'computer-science' },
  { code: 'CS361', title: 'Software Engineering I', description: 'Software development lifecycle, requirements analysis, design, implementation, and testing.', level: 'Undergraduate', credits: 4, outcomes: 'Apply continuous integration|Lead software design sprints|Execute structured testing', universitySlug: 'eastern-oregon-university', subjectSlug: 'computer-science' },
  { code: 'CS221', title: 'C/C++ Programming', description: 'Intermediate to advanced programming concepts using C/C++.', level: 'Undergraduate', credits: 4, outcomes: 'Implement advanced features in C and C++|Understand memory mapping|Write high-performance software', universitySlug: 'eastern-oregon-university', subjectSlug: 'computer-science' },
  { code: 'CS161', title: 'Foundations of Computer Science I', description: 'Introductory programming and computer science fundamentals.', level: 'Undergraduate', credits: 4, outcomes: 'Grasp fundamental programming|Develop analytical thinking|Write initial computing projects', universitySlug: 'eastern-oregon-university', subjectSlug: 'computer-science' },
]
