export const subjects = [
  { name: 'Computer Science', slug: 'computer-science' },
  { name: 'Law', slug: 'law' },
  { name: 'Medicine', slug: 'medicine' },
  { name: 'Engineering', slug: 'engineering' },
  { name: 'Business & Management', slug: 'business-management' },
  { name: 'Psychology', slug: 'psychology' },
  { name: 'Mathematics', slug: 'mathematics' },
  { name: 'Physics', slug: 'physics' },
  { name: 'Economics', slug: 'economics' },
  { name: 'History', slug: 'history' },
]

export const universities = [
  {
    name: 'University of Oxford',
    slug: 'university-of-oxford',
    description: 'The University of Oxford is a collegiate research university in Oxford, England. It is the oldest university in the English-speaking world and the world\'s second-oldest university in continuous operation. Oxford consistently ranks among the top universities globally, renowned for its rigorous academic standards, distinguished alumni, and significant contributions to research and scholarship.',
    location: 'Oxford, England',
    website: 'https://www.ox.ac.uk',
    established: 1096,
    ranking: 1,
  },
  {
    name: 'University of Cambridge',
    slug: 'university-of-cambridge',
    description: 'The University of Cambridge is a public collegiate research university in Cambridge, England. Founded in 1209, Cambridge is the world\'s third-oldest university in continuous operation. It is consistently ranked among the world\'s top universities and is celebrated for excellence in science, humanities, technology, and the arts.',
    location: 'Cambridge, England',
    website: 'https://www.cam.ac.uk',
    established: 1209,
    ranking: 2,
  },
  {
    name: 'Imperial College London',
    slug: 'imperial-college-london',
    description: 'Imperial College London is a public research university in London, England. It is known worldwide for its excellence in science, engineering, medicine, and business. Imperial is consistently ranked among the top 10 universities globally, with a strong emphasis on research impact and innovation.',
    location: 'London, England',
    website: 'https://www.imperial.ac.uk',
    established: 1907,
    ranking: 3,
  },
  {
    name: 'London School of Economics',
    slug: 'london-school-of-economics',
    description: 'The London School of Economics and Political Science (LSE) is a public research university in London, England. LSE is a world-renowned institution for social science, with a focus on economics, politics, law, business, sociology, and related subjects. It has produced numerous Nobel laureates and world leaders.',
    location: 'London, England',
    website: 'https://www.lse.ac.uk',
    established: 1895,
    ranking: 4,
  },
  {
    name: 'University College London',
    slug: 'university-college-london',
    description: 'University College London (UCL) is a public research university in London, England. It is the largest university in London and one of the most prestigious in the UK. UCL is known for its multidisciplinary approach, world-class research, and diverse student community from over 150 countries.',
    location: 'London, England',
    website: 'https://www.ucl.ac.uk',
    established: 1826,
    ranking: 5,
  },
  {
    name: 'University of Edinburgh',
    slug: 'university-of-edinburgh',
    description: 'The University of Edinburgh is a public research university in Edinburgh, Scotland. Founded in 1583, it is one of the oldest and most distinguished universities in Scotland and the UK. Edinburgh consistently ranks among the top 30 universities worldwide and is known for its research in medicine, law, and humanities.',
    location: 'Edinburgh, Scotland',
    website: 'https://www.ed.ac.uk',
    established: 1583,
    ranking: 6,
  },
  {
    name: 'University of Manchester',
    slug: 'university-of-manchester',
    description: 'The University of Manchester is a public research university in Manchester, England. It is a member of the prestigious Russell Group and is renowned for its world-class research. Manchester has produced 25 Nobel Prize winners and is particularly strong in engineering, science, and social sciences.',
    location: 'Manchester, England',
    website: 'https://www.manchester.ac.uk',
    established: 1824,
    ranking: 7,
  },
  {
    name: 'King\'s College London',
    slug: 'kings-college-london',
    description: 'King\'s College London is a public research university located in London, England. It is one of the oldest universities in England and is a founding college of the University of London. King\'s is renowned for its programmes in law, business, humanities, medicine, and the natural and mathematical sciences.',
    location: 'London, England',
    website: 'https://www.kcl.ac.uk',
    established: 1829,
    ranking: 8,
  },
  {
    name: 'University of Bristol',
    slug: 'university-of-bristol',
    description: 'The University of Bristol is a public research university in Bristol, England. It is a member of the Russell Group and is renowned for the quality of its research across science, engineering, arts, and social sciences. Bristol consistently ranks among the top 10 UK universities.',
    location: 'Bristol, England',
    website: 'https://www.bristol.ac.uk',
    established: 1909,
    ranking: 9,
  },
  {
    name: 'University of Warwick',
    slug: 'university-of-warwick',
    description: 'The University of Warwick is a public research university on the outskirts of Coventry, England. Founded in 1965, Warwick has become one of the most prestigious and selective universities in the UK. It is particularly known for its excellence in mathematics, computer science, and business studies.',
    location: 'Coventry, England',
    website: 'https://www.warwick.ac.uk',
    established: 1965,
    ranking: 10,
  },
  {
    name: 'University of Glasgow',
    slug: 'university-of-glasgow',
    description: 'The University of Glasgow is one of Scotland\'s ancient universities, founded in 1451. It is a member of Universitas 21 and the Russell Group. Glasgow is renowned for its research in engineering, medicine, social sciences, and arts, with a vibrant campus in one of Scotland\'s most exciting cities.',
    location: 'Glasgow, Scotland',
    website: 'https://www.gla.ac.uk',
    established: 1451,
    ranking: 11,
  },
  {
    name: 'Durham University',
    slug: 'durham-university',
    description: 'Durham University is a collegiate public research university in Durham, England. Founded in 1832, it is one of the oldest universities in England and offers a distinctive collegiate experience. Durham is highly regarded for academics, student life and sports, consistently ranking in the top 10 UK universities.',
    location: 'Durham, England',
    website: 'https://www.durham.ac.uk',
    established: 1832,
    ranking: 12,
  },
  {
    name: 'University of Sheffield',
    slug: 'university-of-sheffield',
    description: 'The University of Sheffield is a public research university in Sheffield, South Yorkshire, England. It is a member of the Russell Group and is ranked among the top 100 universities in the world. Sheffield is particularly noted for engineering, medicine, and social sciences.',
    location: 'Sheffield, England',
    website: 'https://www.sheffield.ac.uk',
    established: 1905,
    ranking: 13,
  },
  {
    name: 'University of Southampton',
    slug: 'university-of-southampton',
    description: 'The University of Southampton is a public research university in Southampton, England. It is a member of the Russell Group and is particularly well known for its world-leading research in electronics, engineering, oceanography, and medicine.',
    location: 'Southampton, England',
    website: 'https://www.southampton.ac.uk',
    established: 1952,
    ranking: 14,
  },
  {
    name: 'University of Leeds',
    slug: 'university-of-leeds',
    description: 'The University of Leeds is a public research university in Leeds, West Yorkshire, England. A member of the Russell Group, Leeds is known for its wide range of high-quality academic programmes, internationally recognised research, and its vibrant student community.',
    location: 'Leeds, England',
    website: 'https://www.leeds.ac.uk',
    established: 1904,
    ranking: 15,
  },
  {
    name: 'University of Birmingham',
    slug: 'university-of-birmingham',
    description: 'The University of Birmingham is a public research university in the Edgbaston area of Birmingham, England. It was the first civic university to be established in England and is a founding member of the Russell Group. Birmingham is particularly strong in science, engineering, and social sciences.',
    location: 'Birmingham, England',
    website: 'https://www.birmingham.ac.uk',
    established: 1900,
    ranking: 16,
  },
  {
    name: 'Queen Mary University of London',
    slug: 'queen-mary-university-of-london',
    description: 'Queen Mary University of London is a public research university in London, England. It is a member of the Russell Group and known for its world-class research in law, medicine, engineering, and the humanities. Its Mile End campus is one of London\'s most self-contained university communities.',
    location: 'London, England',
    website: 'https://www.qmul.ac.uk',
    established: 1885,
    ranking: 17,
  },
  {
    name: 'University of Exeter',
    slug: 'university-of-exeter',
    description: 'The University of Exeter is a public research university headquartered in Exeter, Devon, England. It is a member of the Russell Group and consistently ranked among the top 15 UK universities. Exeter is particularly recognised for its research in environmental science, business, and the humanities.',
    location: 'Exeter, England',
    website: 'https://www.exeter.ac.uk',
    established: 1955,
    ranking: 18,
  },
  {
    name: 'University of Bath',
    slug: 'university-of-bath',
    description: 'The University of Bath is a public research university in Bath, Somerset, England. Bath consistently achieves superb academic results and regularly appears in the top 10 of major UK league tables. It is known for its strong links with industry, particularly in engineering, business, and science.',
    location: 'Bath, England',
    website: 'https://www.bath.ac.uk',
    established: 1966,
    ranking: 19,
  },
  {
    name: 'Newcastle University',
    slug: 'newcastle-university',
    description: 'Newcastle University is a public research university in Newcastle upon Tyne, England. It is a member of the Russell Group and is ranked in the top 1% of universities worldwide. Newcastle is known for its research excellence in medicine, engineering, and social sciences.',
    location: 'Newcastle upon Tyne, England',
    website: 'https://www.ncl.ac.uk',
    established: 1834,
    ranking: 20,
  },
]

export const courses = [
  // Computer Science
  {
    code: 'CSC101',
    title: 'Introduction to Computer Science',
    description: 'An introductory course covering the fundamental principles of computer science, including problem-solving techniques, algorithmic thinking, basic data structures, and an introduction to programming paradigms. Students will gain a solid grounding in the theoretical and practical aspects of computing.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Understand core CS concepts; Write simple algorithms; Analyse computational problems; Use basic data structures',
    universitySlug: 'university-of-oxford',
    subjectSlug: 'computer-science',
  },
  {
    code: 'CSC232',
    title: 'Data Structures and Algorithms',
    description: 'A comprehensive study of fundamental data structures and algorithms used in computer science. Topics include arrays, linked lists, trees, graphs, sorting and searching algorithms, algorithm complexity analysis, and design paradigms such as divide-and-conquer and dynamic programming.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Implement and analyse data structures; Design efficient algorithms; Apply Big-O notation; Solve complex computational problems',
    universitySlug: 'university-of-cambridge',
    subjectSlug: 'computer-science',
  },
  {
    code: 'CSC340',
    title: 'Artificial Intelligence',
    description: 'An exploration of the principles and practice of artificial intelligence. Topics include search algorithms, machine learning, neural networks, natural language processing, computer vision, and the ethical implications of AI. Students will implement AI systems through practical projects.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Apply core AI techniques; Implement machine learning models; Understand ethical AI considerations; Build AI-powered applications',
    universitySlug: 'university-of-manchester',
    subjectSlug: 'computer-science',
  },
  {
    code: 'CSC451',
    title: 'Software Engineering',
    description: 'This course covers the systematic approach to the design, development, operation, and maintenance of software systems. Topics include requirements engineering, software architecture, design patterns, testing methodologies, agile development practices, and software project management.',
    level: 'Undergraduate',
    credits: 30,
    outcomes: 'Design software systems; Apply design patterns; Lead agile sprints; Write comprehensive test suites',
    universitySlug: 'imperial-college-london',
    subjectSlug: 'computer-science',
  },
  {
    code: 'CSC560',
    title: 'Machine Learning',
    description: 'A rigorous treatment of machine learning theory and practice. The course covers supervised and unsupervised learning, probabilistic models, support vector machines, ensemble methods, neural networks, and deep learning. Students will work on real-world datasets through assignments and a final project.',
    level: 'Postgraduate',
    credits: 20,
    outcomes: 'Build and evaluate ML models; Apply deep learning techniques; Handle real-world datasets; Understand mathematical foundations of ML',
    universitySlug: 'university-of-edinburgh',
    subjectSlug: 'computer-science',
  },
  {
    code: 'CSC620',
    title: 'Cybersecurity',
    description: 'This course provides a comprehensive overview of cybersecurity principles and practices. Students will study network security, cryptography, secure software development, ethical hacking, incident response, and the legal and regulatory frameworks governing information security.',
    level: 'Postgraduate',
    credits: 30,
    outcomes: 'Identify security vulnerabilities; Apply cryptographic protocols; Conduct ethical penetration testing; Develop incident response plans',
    universitySlug: 'university-college-london',
    subjectSlug: 'computer-science',
  },
  {
    code: 'CSC710',
    title: 'Cloud Computing',
    description: 'A study of cloud computing concepts, architectures, and services. Topics include virtualization, containerization, microservices, serverless computing, distributed systems, cloud security, and major cloud platform services (AWS, Azure, GCP). Students will build and deploy cloud-native applications.',
    level: 'Postgraduate',
    credits: 20,
    outcomes: 'Architect cloud-native systems; Deploy containerized applications; Manage cloud infrastructure; Apply distributed computing principles',
    universitySlug: 'university-of-warwick',
    subjectSlug: 'computer-science',
  },
  // Law
  {
    code: 'LAW101',
    title: 'Introduction to English Law',
    description: 'A foundational course introducing students to the principles, sources, and institutions of English law. Topics include the structure of the English legal system, key areas of public and private law, legal reasoning, statutory interpretation, and an introduction to contract and tort.',
    level: 'Undergraduate',
    credits: 30,
    outcomes: 'Understand the English legal system; Apply basic legal reasoning; Read and analyse case law; Write basic legal essays',
    universitySlug: 'university-of-oxford',
    subjectSlug: 'law',
  },
  {
    code: 'LAW201',
    title: 'Contract Law',
    description: 'This course provides a thorough grounding in the law of contract. It examines the formation of contracts, contractual terms, vitiating factors, and remedies for breach. Students will analyse leading cases and learn to apply legal principles to complex factual scenarios.',
    level: 'Undergraduate',
    credits: 30,
    outcomes: 'Analyse contract formation; Identify vitiating factors; Apply contract remedies; Draft basic contractual clauses',
    universitySlug: 'kings-college-london',
    subjectSlug: 'law',
  },
  {
    code: 'LAW301',
    title: 'Constitutional and Administrative Law',
    description: 'An analysis of the UK constitution, covering parliamentary sovereignty, the rule of law, judicial review, human rights law, and administrative law principles. Students will examine the constitutional arrangements of the UK and how public bodies exercise their powers.',
    level: 'Undergraduate',
    credits: 30,
    outcomes: 'Analyse constitutional principles; Understand judicial review; Apply human rights frameworks; Evaluate administrative decisions',
    universitySlug: 'london-school-of-economics',
    subjectSlug: 'law',
  },
  {
    code: 'LAW450',
    title: 'International Law',
    description: 'A comprehensive study of public international law covering its sources, subjects, and key areas of application including human rights, use of force, international environmental law, and dispute resolution mechanisms. Students engage with primary international legal materials.',
    level: 'Undergraduate',
    credits: 30,
    outcomes: 'Identify international law sources; Apply treaty law; Understand state responsibility; Analyse international dispute resolution',
    universitySlug: 'university-of-edinburgh',
    subjectSlug: 'law',
  },
  // Medicine
  {
    code: 'MED101',
    title: 'Foundations of Medicine',
    description: 'An introductory course covering the biological, physiological, and biochemical foundations essential for medical study. Topics include cell biology, genetics, anatomy, physiology, biochemistry, and an introduction to pathological processes. The course integrates scientific theory with clinical application.',
    level: 'Undergraduate',
    credits: 40,
    outcomes: 'Understand human anatomy and physiology; Apply biochemistry to disease; Recognise pathological processes; Integrate basic science with clinical reasoning',
    universitySlug: 'university-of-cambridge',
    subjectSlug: 'medicine',
  },
  {
    code: 'MED302',
    title: 'Clinical Practice',
    description: 'A clinically-focused module that develops students\' skills in taking patient histories, physical examination, clinical reasoning, and communication. Students will undertake placements in clinical environments and learn to work effectively within healthcare teams.',
    level: 'Undergraduate',
    credits: 40,
    outcomes: 'Conduct thorough patient histories; Perform physical examinations; Apply clinical reasoning; Communicate effectively with patients',
    universitySlug: 'imperial-college-london',
    subjectSlug: 'medicine',
  },
  {
    code: 'MED501',
    title: 'Pharmacology',
    description: 'A systematic study of the science of drugs, covering pharmacokinetics, pharmacodynamics, drug classification, mechanisms of action, therapeutic uses, and adverse effects. Students will develop the ability to make safe and effective prescribing decisions.',
    level: 'Undergraduate',
    credits: 30,
    outcomes: 'Understand drug mechanisms of action; Apply pharmacokinetic principles; Make safe prescribing decisions; Identify adverse drug reactions',
    universitySlug: 'university-college-london',
    subjectSlug: 'medicine',
  },
  // Engineering
  {
    code: 'ENG101',
    title: 'Engineering Mathematics',
    description: 'A core mathematics module covering the mathematical tools essential for engineering. Topics include calculus, linear algebra, differential equations, probability and statistics, and numerical methods. Students will apply mathematical techniques to engineering problems.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Apply calculus to engineering; Solve differential equations; Use linear algebra; Apply statistical methods to data',
    universitySlug: 'imperial-college-london',
    subjectSlug: 'engineering',
  },
  {
    code: 'ENG220',
    title: 'Structural Engineering',
    description: 'This course covers the principles of structural analysis and design. Topics include statics, mechanics of materials, structural members, load analysis, and the design of steel and concrete structures to British and European standards. Practical laboratory sessions reinforce theoretical concepts.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Analyse structural loads; Design structural members; Apply Eurocode standards; Conduct structural calculations',
    universitySlug: 'university-of-bristol',
    subjectSlug: 'engineering',
  },
  {
    code: 'ENG330',
    title: 'Electrical and Electronic Engineering',
    description: 'An introduction to electrical circuits, electronic devices, signals and systems, and digital electronics. Students will study circuit analysis, operational amplifiers, and digital logic. Laboratory sessions provide hands-on experience with circuit design and measurement.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Analyse electrical circuits; Design basic electronic systems; Apply digital logic; Use electronic test equipment',
    universitySlug: 'university-of-manchester',
    subjectSlug: 'engineering',
  },
  {
    code: 'ENG440',
    title: 'Mechanical Design',
    description: 'A project-centred course covering CAD modelling, manufacturing processes, materials selection, and machine element design. Students will use industry-standard CAD software to design and virtually prototype mechanical components and systems.',
    level: 'Undergraduate',
    credits: 30,
    outcomes: 'Create 3D CAD models; Select appropriate materials; Apply design standards; Conduct virtual prototyping',
    universitySlug: 'university-of-sheffield',
    subjectSlug: 'engineering',
  },
  // Business
  {
    code: 'BUS101',
    title: 'Introduction to Business Management',
    description: 'A comprehensive introduction to the world of business, covering organisational structures, management principles, marketing fundamentals, financial awareness, human resource management, and business strategy. Students will explore both theory and practice through case studies.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Understand organisational structures; Apply management principles; Analyse business strategy; Read financial statements',
    universitySlug: 'london-school-of-economics',
    subjectSlug: 'business-management',
  },
  {
    code: 'BUS250',
    title: 'Marketing Management',
    description: 'This course explores the principles and practice of marketing in both B2C and B2B contexts. Topics include market research, consumer behaviour, segmentation and targeting, the marketing mix, digital marketing, brand management, and marketing communications.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Develop marketing strategies; Conduct market research; Manage brand positioning; Plan integrated marketing campaigns',
    universitySlug: 'university-of-warwick',
    subjectSlug: 'business-management',
  },
  {
    code: 'BUS360',
    title: 'Corporate Finance',
    description: 'An in-depth study of financial decision-making within corporations. Topics include capital budgeting, cost of capital, capital structure, dividend policy, working capital management, mergers and acquisitions, and corporate governance. The course develops both theoretical understanding and analytical skills.',
    level: 'Undergraduate',
    credits: 30,
    outcomes: 'Apply capital budgeting techniques; Analyse capital structure decisions; Evaluate M&A transactions; Assess corporate governance',
    universitySlug: 'university-of-bristol',
    subjectSlug: 'business-management',
  },
  // Psychology
  {
    code: 'PSY101',
    title: 'Introduction to Psychology',
    description: 'A survey of the major areas of psychological science, including biological, cognitive, developmental, social, and clinical psychology. Students will explore the scientific foundations of psychology and develop critical thinking skills for evaluating psychological evidence.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Understand major psychological perspectives; Evaluate psychological research; Apply psychological concepts; Write psychology research reports',
    universitySlug: 'university-of-oxford',
    subjectSlug: 'psychology',
  },
  {
    code: 'PSY220',
    title: 'Cognitive Psychology',
    description: 'An exploration of human mental processes including attention, perception, memory, language, problem solving, and decision making. The course examines computational and neuroscientific approaches to understanding the mind, with an emphasis on experimental methods.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Understand cognitive processes; Apply experimental methods; Interpret cognitive neuroscience findings; Design cognitive experiments',
    universitySlug: 'university-of-cambridge',
    subjectSlug: 'psychology',
  },
  // Mathematics
  {
    code: 'MTH101',
    title: 'Calculus and Analysis',
    description: 'A rigorous introduction to real analysis and calculus, covering limits, continuity, differentiation, integration, sequences and series, and functions of several variables. This course develops the mathematical maturity and proof-writing skills essential for advanced mathematics.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Write rigorous mathematical proofs; Apply differential and integral calculus; Analyse sequences and series; Work with multivariable functions',
    universitySlug: 'university-of-cambridge',
    subjectSlug: 'mathematics',
  },
  {
    code: 'MTH210',
    title: 'Linear Algebra',
    description: 'A foundational course in linear algebra covering vector spaces, linear transformations, matrices, determinants, eigenvalues and eigenvectors, and inner product spaces. Applications to geometry, differential equations, and data science are explored.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Work with vector spaces; Apply linear transformations; Compute eigenvalues; Use linear algebra in applications',
    universitySlug: 'university-of-oxford',
    subjectSlug: 'mathematics',
  },
  // Physics
  {
    code: 'PHY101',
    title: 'Classical Mechanics',
    description: 'A rigorous treatment of Newtonian and Lagrangian mechanics, covering kinematics, dynamics, conservation laws, oscillations, waves, rigid body dynamics, and an introduction to Hamiltonian mechanics. The course develops students\' mathematical problem-solving skills.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Apply Newton\'s laws; Use Lagrangian mechanics; Solve oscillation problems; Analyse rigid body dynamics',
    universitySlug: 'imperial-college-london',
    subjectSlug: 'physics',
  },
  {
    code: 'PHY301',
    title: 'Quantum Mechanics',
    description: 'An introduction to the foundational principles of quantum mechanics, including wave-particle duality, the Schrödinger equation, quantum states and measurements, the uncertainty principle, harmonic oscillator, hydrogen atom, and spin. Students will develop mathematical tools for quantum theory.',
    level: 'Undergraduate',
    credits: 30,
    outcomes: 'Apply quantum postulates; Solve the Schrödinger equation; Understand quantum measurement; Calculate atomic spectra',
    universitySlug: 'university-of-oxford',
    subjectSlug: 'physics',
  },
  // Economics
  {
    code: 'ECO101',
    title: 'Principles of Economics',
    description: 'An introduction to both microeconomics and macroeconomics. Topics include supply and demand, market equilibrium, consumer and producer theory, market structures, national income accounting, inflation, unemployment, monetary and fiscal policy.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Apply supply and demand analysis; Understand market structures; Analyse macroeconomic policy; Interpret economic data',
    universitySlug: 'london-school-of-economics',
    subjectSlug: 'economics',
  },
  {
    code: 'ECO250',
    title: 'Econometrics',
    description: 'This course introduces students to the statistical methods used to analyse economic data. Topics include simple and multiple regression analysis, hypothesis testing, instrumental variables, panel data methods, and time series analysis. Students will use statistical software for data analysis.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Conduct regression analysis; Test economic hypotheses; Analyse panel data; Use statistical software',
    universitySlug: 'university-of-warwick',
    subjectSlug: 'economics',
  },
  // History
  {
    code: 'HIS101',
    title: 'British History: 1066–1485',
    description: 'A survey of British history from the Norman Conquest to the Wars of the Roses. Students will explore key political, social, economic, and cultural developments of medieval Britain, examining primary sources and historiographical debates.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Analyse primary historical sources; Understand medieval Britain; Engage with historiographical debate; Write historical essays',
    universitySlug: 'university-of-oxford',
    subjectSlug: 'history',
  },
  {
    code: 'HIS302',
    title: 'Modern British History: 1900–2000',
    description: 'An examination of Britain\'s transformative twentieth century, covering the World Wars, the welfare state, decolonisation, social change, economic decline and revival, and Britain\'s changing role in the world. Students engage with a wide range of primary and secondary sources.',
    level: 'Undergraduate',
    credits: 20,
    outcomes: 'Analyse 20th-century British history; Evaluate primary sources; Understand social change; Construct historical arguments',
    universitySlug: 'university-of-edinburgh',
    subjectSlug: 'history',
  },
]
